# Generated by Django 4.2.7 on 2025-10-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
    ]
